export {default as Hallazgos} from './Hallazgos'
export {default as Dashboard} from './Dashboard'
export {default as ChartArea} from './ChartArea'
export {default as ChartPrioridad} from './ChartPrioridad'
export {default as ChartStatus} from './ChartStatus'