export {default as Form} from './Form/Form'
export {default as Posts} from './Posts/Posts'
export {default as Navbar} from './Navbar/Navbar'
export {default as Home} from './Home/Home'
export {default as Auth} from './Auth/Auth'
export {default as Input} from './Auth/Input'
export {default as Paginate} from './Pagination'
export {default as PostDetails} from './PostDetails/PostDetails'
